############################
## CHANGE THESE
############################

baseURL: "https://michaelanthonymain.github.io/presidents"
title: presidents

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
