############################
## CHANGE THESE
############################

baseURL: "www.presidentsinouterspace.com"
title: The. Moon

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
