############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Episodes
  url: /episodes/
  weight: 20
- name: About
  url: /about/
  weight: 30
